version: "3"
services:
  file-server:
    ports:
      - 5000:5000
    build: .
    volumes:
      - ./files/images:/files/images
    environment:
      DATABASE_URL: postgres://file-server:@db:5432/file-server?sslmode=disable
      PORT: :5000
      IMAGE_MAX_WIDTH: 3000
      IMAGE_MAX_HEIGHT: 2000
  db:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: file-server
    image: postgres:11.2-alpine
