name: CI

on:
  push:
    branches:
      - "master"
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.14.2
      - name: Check out code
        uses: actions/checkout@master
      - name: Up fake database
        run: docker-compose up -d dbtest
      - name: install pngquant
        run: sudo apt-get install -y pngquant
      - name: Test
        run: go test ./server
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: thanhtuan2605/image-server
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
