name: Push master

on:
  push:
    branches:
      - "master"
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image-server
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      # Build the Docker image
      - name: Build
        run: docker build -t $IMAGE_NAME .
