name: Release

on:
  release:
    types:
      - published
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image-server
jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      # Build the Docker image
      - name: Build
        run: docker build -t $IMAGE_NAME .
      - name: Login github package
        run: docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password ${{secrets.GITHUB_TOKEN}}
      - name: Tag package
        run: docker tag $IMAGE_NAME docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:${GITHUB_REF##*/}
      - name: Publish
        run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$IMAGE_NAME:${GITHUB_REF##*/}
