name: CI

on:
  release:
    types:
      - published
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: file-server
jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      # Build the Docker image
      - name: Build
        run: docker build -t $IMAGE_NAME .
      - name: Login github package
        run: docker login docker.pkg.github.com -u thanhtuan260593 --password ${{secrets.PACKAGE_TOKEN}}
      - name: Tag package
        run: docker tag $IMAGE_NAME docker.pkg.github.com/thanhtuan260593/file-server/$IMAGE_NAME:${GITHUB_REF##*/}
      - name: Publish
        run: docker push docker.pkg.github.com/thanhtuan260593/file-server/$IMAGE_NAME:${GITHUB_REF##*/}
