name: CI

on:
  release:
    types:
      - published
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.14.2
      - name: Check out code
        uses: actions/checkout@master
      - name: Up fake database
        run: docker-compose up -d dbtest
      - name: install pngquant
        run: sudo apt-get install -y pngquant
      - name: Test
        run: go test ./server/... --coverprofile coverage.out
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.out

  build:
    name: Build and push
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@master
      # Build the Docker image
      - name: Build
        run: docker build -t $IMAGE:${GITHUB_REF##*/}
      - name: Publish
        run: docker push docker.pkg.github.com/thanhtuan260593/file-server/$IMAGE:${GITHUB_REF##*/}
